export const TYPE = {
    GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
    GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES',
    FILTER_BY_CATEGORIES: 'FILTER_BY_CATEGORIES',
    FIND_PRODUCT_BY_ID: 'FIND_PRODUCT_BY_ID',
    ADD_TO_CART: 'ADD_TO_CART',

    CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',

    INCREMENT_PRODUCT_CART: 'INCREMENT_PRODUCT_CART',
    DECREMENT_PRODUCT_CART: 'DECREMENT_PRODUCT_CART',
    DELETE_PRODUCT_CART: 'DELETE_PRODUCT_CART',

}




